/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as RobotsDottxtRouteImport } from './routes/robots[.]txt'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as WhatWeSourceRouteImport } from './routes/what-we-source'
import { Route as WhoWeWorkWithRouteImport } from './routes/who-we-work-with'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const RobotsDottxtRoute = RobotsDottxtRouteImport.update({
  id: '/robots.txt',
  path: '/robots.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const WhatWeSourceRoute = WhatWeSourceRouteImport.update({
  id: '/what-we-source',
  path: '/what-we-source',
  getParentRoute: () => rootRouteImport,
} as any)
const WhoWeWorkWithRoute = WhoWeWorkWithRouteImport.update({
  id: '/who-we-work-with',
  path: '/who-we-work-with',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/register': typeof RegisterRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/what-we-source': typeof WhatWeSourceRoute
  '/who-we-work-with': typeof WhoWeWorkWithRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/register': typeof RegisterRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/what-we-source': typeof WhatWeSourceRoute
  '/who-we-work-with': typeof WhoWeWorkWithRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/register': typeof RegisterRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/what-we-source': typeof WhatWeSourceRoute
  '/who-we-work-with': typeof WhoWeWorkWithRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/register'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/what-we-source'
    | '/who-we-work-with'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/register'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/what-we-source'
    | '/who-we-work-with'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/register'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/what-we-source'
    | '/who-we-work-with'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  RegisterRoute: typeof RegisterRoute
  RobotsDottxtRoute: typeof RobotsDottxtRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  WhatWeSourceRoute: typeof WhatWeSourceRoute
  WhoWeWorkWithRoute: typeof WhoWeWorkWithRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/robots.txt': {
      id: '/robots.txt'
      path: '/robots.txt'
      fullPath: '/robots.txt'
      preLoaderRoute: typeof RobotsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/what-we-source': {
      id: '/what-we-source'
      path: '/what-we-source'
      fullPath: '/what-we-source'
      preLoaderRoute: typeof WhatWeSourceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/who-we-work-with': {
      id: '/who-we-work-with'
      path: '/who-we-work-with'
      fullPath: '/who-we-work-with'
      preLoaderRoute: typeof WhoWeWorkWithRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  RegisterRoute: RegisterRoute,
  RobotsDottxtRoute: RobotsDottxtRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  WhatWeSourceRoute: WhatWeSourceRoute,
  WhoWeWorkWithRoute: WhoWeWorkWithRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
